AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bedrock GenAI Gameday Lambda Function
  
  Sample SAM Template for a Lambda function with API Gateway trigger
  and full permissions to DynamoDB, S3, Step Functions, Bedrock, and CloudWatch

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs20.x

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-gameday-lambda
      CodeUri: ./
      Handler: src/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Description: Lambda function with API Gateway trigger
      Environment:
        Variables:
          LOG_LEVEL: INFO
          # Bedrock Model Configuration - COST CONTROL
          # Using Claude Haiku (cheapest) for practice/testing
          # Change to anthropic.claude-3-opus-20240229-v1:0 if needed (expensive!)
          BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          MAX_INPUT_LENGTH: "1000"
          MAX_TOKENS: "1024"
          APP_REGION: !Ref AWS::Region
          # API key resolved from SSM Parameter Store using CloudFormation dynamic reference
          # Note: Use 'ssm-secure' for SecureString, 'ssm' for String type
          BEDROCK_API_KEY: !Sub "{{resolve:ssm:/poc/bedrock-api-key}}"
          DYNAMODB_TABLE_NAME: !Ref QueryCacheTable
          S3_BUCKET_NAME: "gameday-bedrock"
          S3_DOCUMENT_KEY: "travel_details.md"
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: post
            RestApiId: !Ref HelloWorldApi
        SuggestionsApi:
          Type: Api
          Properties:
            Path: /suggestions
            Method: get
            RestApiId: !Ref HelloWorldApi
      Role: !GetAtt LambdaExecutionRole.Arn

  # DynamoDB Table for Query Cache
  QueryCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: travelbuddy-query-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: queryHash
          AttributeType: S
      KeySchema:
        - AttributeName: queryHash
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false

  # API Gateway
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # IAM Role for Lambda with full permissions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !GetAtt QueryCacheTable.Arn
        - PolicyName: S3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
        - PolicyName: StepFunctionsFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:*
                Resource: "*"
        - PolicyName: BedrockFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:*
                Resource: "*"
        - PolicyName: CloudWatchFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - cloudwatch:*
                Resource: "*"

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Dev stage"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello"
  
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaExecutionRole.Arn
  
  QueryCacheTable:
    Description: "DynamoDB Table for Query Cache"
    Value: !Ref QueryCacheTable

